### ISSUE TITLE
Flummox's Actions.js grabs all console logs

### ISSUE THREAD

**Issue by chetanism** [gaearon/dnd-core#17]
Hi, I created this issue with the flummox library: https://github.com/acdlite/flummox/issues/264.

My problem is that under chrome browser all my logs/errors/warnings are shown to be logged from Actions.js. This is very frustrating because now I don't see the filename/line number where error is. 

I see that in flummox's master branch the file is removed. Can you please check if it would be possible to bump up the flummox version or replace it with redux (as suggested on flummox's page). Or let me know if you know any workaround. Following is a screenshot from my browser:

<img width="1272" alt="screen shot 2015-07-17 at 1 23 16 pm" src="https://cloud.githubusercontent.com/assets/2418542/8743257/ce29d652-2c8a-11e5-991b-e38381da81df.png">

Thanks
chetan.

**Comment by gaearon** [comment]
I'm closing because this is unrelated to dnd-core—for some reason, the source you're getting is broken.
dnd-core is just a library and can't influence that.
