### ISSUE TITLE
endDrop notification.

### ISSUE THREAD

**Issue by is** [gaearon/dnd-core#20]
DropTarget component can get drag object enter or leave state by isOver changes through componentWillReceiveProps method. I want to know any simple way to tell targets the drag is end.

I see dragSource has endDrop callback. it's possible implement in dropTarget?

**Comment by gaearon** [comment]
Only the drop target that received the drop will have `drop()` hook called. If you want all drop targets to react to an arbitrary drop, you'll need to arrange this manually.

You can also check changes of `isDragging` in `componentWillReceiveProps`. When it changes from `true` to `false`, it means the drop has occurred.
