### ISSUE TITLE
Drop action nulls dragOffsets

### ISSUE THREAD

**Issue by scottlangendyk** [gaearon/dnd-core#23]
Based on the tests this is expected behavior, but I'm not sure it should be.

For example, a listener that renders the drag might rely on monitor.isDragging() and monitor.getSourceClientOffset(), as you demonstrate in examples for react-dnd's DragLayer.

**Comment by gaearon** [comment]
Can you expand on why this is an issue?

Once you drop, why would it be important to keep the offsets?
At this point technically nothing is being dragged.

I’ll close for now as I don’t see this as actionable but please let me know if you have a specific scenario in mind, and I’ll be happy to reopen.
