### ISSUE TITLE
Idea: Integrate With External Redux Store

### ISSUE THREAD

**Issue by aldendaniels** [gaearon/dnd-core#26]
An idea I had - feel free to close if this is unlikely to make the roadmap.

When using ReactDnD in a Redux app, it would be nice if the drag/drop state were stored in the primary app store and updated via Redux actions. Currently `dnd-core` stores the drag/drop state in its own internal store.

 This change would let you automatically debug drag/drop state via Redux Dev tools.

I imagined this could accomplished using the same approach that https://github.com/rackt/react-router-redux adopts: by providing a reducer and middleware and firing actions at the main application store.

**Comment by gaearon** [comment]
While technically this is doable I’m afraid it won’t be performant enough.
Still please feel free to fork and try this. Shouldn’t be hard to do.
If it works well we can support this, but I’m unlikely to work on it.
